### ISSUE TITLE
Generated tilemap hides animation preview choice on wide monitors

### ISSUE THREAD

**Issue by Loufe** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#180] opened 2024-07-22 17:21 UTC
Hi there,

On my ultrawide the css doesn't quite work correctly:
![image](https://github.com/user-attachments/assets/45b44227-584f-46e0-bf28-e99fd20e875a)

If I make the window half-screen, it works as (I imagine is) intended:
![image](https://github.com/user-attachments/assets/d9fdc248-a79d-453d-9a81-80fdbba436a2)

Thanks for the excellent tool.

**Comment by jrconway3** [comment] 2024-10-15 17:02
I wonder if I could test this by connecting my laptop up to my big TV. Not sure how else I could test this issue.

**Comment by jrconway3** [comment] 2024-11-01 00:18
Oh, there we go. I put this on my big monitor and now I can see the issue. I'll try putting out a fix for this in the next PR.

**Comment by jrconway3** [comment] 2024-11-01 00:25
This is caused by vertical-align. What's happening is that, for some reason, the "Preview" and select box are lining up at the bottom (or perhaps center) of the canvas at the top. Normally, they sit on "Top" of each other, because the browser window is less wide. When you expand the browser window, however, they are able to sit side-by-side, but the vertical-align shoves the Preview and select box down further.

**Comment by Loufe** [comment] 2024-11-01 03:31
You're amazing, thank you, JR.

**Comment by jrconway3** [comment] 2024-11-01 03:41
Well I do web development for a living, so I already know all about how to debug web pages lol. The only issue is I needed to know how to reproduce it first. Apparently my monitor was already big enough to see the issue, I just never opened it up on that specific monitor.

**Comment by jrconway3** [comment] 2024-11-01 23:24
@Loufe Please let me know how this looks now, the update has been deployed.

**Comment by Loufe** [comment] 2024-11-02 01:39
> @Loufe Please let me know how this looks now, the update has been deployed.

LGTM, good work

![image](https://github.com/user-attachments/assets/fddb295d-c7d0-45ae-91ba-465ea9f02d92)

**Comment by jrconway3** [comment] 2024-11-02 05:49
Can you close this issue then?

**Closed as completed** 2024-11-02 18:54 UTC
Labels: enhancement, help wanted
