### ISSUE TITLE
BackSlash model issue

### ISSUE THREAD

**Issue by LuciferRules** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#202] opened 2024-10-26 01:05 UTC
Really nice sprites generator, this is i am looking for.
Seems like there is a bug configuring the backslash animation, the hairs/head/ clothes/boots cannot be equiped.
![sample](https://github.com/user-attachments/assets/30fc89f6-3c3a-482b-a4b4-47a62c5a6182)

**Comment by jrconway3** [comment] 2024-10-26 06:05
Not a bug, just that not everything is implemented yet. Please use the Animations filters. There are plenty of assets that do support Backslash, but there's still tons that aren't ready yet. The newer animations were only more recently added and not many people have added assets for these newer animations (that includes run/jump/etc).

**Comment by jrconway3** [comment] 2024-10-27 19:09
In any case, I don't think there's a need for this card. There's already other issues in here addressing the fact that there's missing assets. And we already had an issue talking about missing assets before and the solution we implemented was the "Animations" filter, which let's you filter assets based on which animations are supported.

https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/issues/88

I get that it sucks not all assets are filled out yet, but it takes a ton of work to get done.

**Comment by jrconway3** [comment] 2024-10-28 01:44
Here's something that you can do:

When you find specific assets that aren't showing up and you really want them to work, please create a card for those specific assets. That gives me an idea of what to prioritize. That said, clothing is never high priority because it takes a long, long time to finish clothing assets. So please keep that in mind.

Whatever the case may be, though, please create an issue as to which assets you'd like done first, and I'll try to get to them as soon as I can. Otherwise, it will all be done on my own priority when I feel comfortable getting to it. Not many people are working on these assets right now either.

**Comment by jrconway3** [comment] 2024-10-29 15:19
I double-checked the preview image of this card and I see that you're looking at armor specifically. I went ahead and created a new card handling a complete breakdown of what's there to do on armor (#205).

I cannot guarantee I'll get to it soon, but I have created a card. I think this might be easier to do than clothes because armor is compartmentalized into different body parts, so I don't have to get the whole thing done at once. I can do individual types on its own.


If you have any other prioritizes you'd like to see, please create a card that explains _which_ assets you are missing that you want to see. Over time, though, I will create more cards outlining which assets are still missing.

**Comment by jrconway3** [comment] 2024-11-06 16:42
The first armour piece is available now, its Plate Body available on Male, Teen, and Female. I am looking into how difficult it is to do Leather and Legion, but I plan to have them out within the next two weeks.

**Comment by jrconway3** [comment] 2024-12-25 18:02
I get the way it looks is off, but this is really just a duplicate of:
https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/issues/88

@sanderfrenken I think we should close this card as a duplicate. I am working on these assets, but its going to take a long time to get them done.

**Closed as not planned** 2024-12-27 16:34 UTC
